# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-08-09 15:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=20)),
                ('journey_pattern', models.CharField(max_length=20)),
                ('headsign', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Route')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lon', models.FloatField()),
                ('name', models.CharField(blank=True, default='None', max_length=250)),
                ('stop_id', models.IntegerField(unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='routestation',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='bus.RouteStation', to='bus.Stop'),
        ),
        migrations.AlterUniqueTogether(
            name='routestation',
            unique_together=set([('stop', 'route')]),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('route_id', 'journey_pattern')]),
        ),
    ]
