# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-13 11:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(max_length=20)),
                ('journey_pattern', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Route')),
            ],
        ),
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(blank=True, default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.AddField(
            model_name='routestation',
            name='stop',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Stop'),
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='bus.RouteStation', to='bus.Stop'),
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('route_id', 'journey_pattern')]),
        ),
    ]
