# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 16:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0003_auto_20170710_1508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='route',
            name='journey_pattern',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='route',
            name='route_id',
            field=models.IntegerField(),
        ),
    ]
