# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-10 17:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0005_auto_20170710_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='RouteStation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Route')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bus.Stop')),
            ],
        ),
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='bus.RouteStation', to='bus.Stop'),
        ),
    ]
