# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0006_auto_20170710_1757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(blank=True, default='None', max_length=250),
        ),
        migrations.AlterField(
            model_name='stop',
            name='stop_id',
            field=models.IntegerField(unique=True),
        ),
        migrations.RemoveField(
            model_name='route',
            name='stops',
        ),
        migrations.AlterUniqueTogether(
            name='route',
            unique_together=set([('route_id', 'journey_pattern')]),
        ),
    ]
