# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-11 21:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0007_auto_20170711_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='stops',
            field=models.ManyToManyField(through='bus.RouteStation', to='bus.Stop'),
        ),
    ]
