# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-04 10:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bus', '0008_route_stops'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='routestation',
            unique_together=set([('stop', 'route')]),
        ),
    ]
